# Optimized mix config — auto-generated by track_analyzer.py
# Tracks: 21
# BPM range: 120 - 128
# Camelot path: 12B → 12A → 11A → 11A → 10A → 10B → 10A → 9B → 8B → 8A → 7A → 6A → 6A → 6A → 4A → 4A → 4A → 3B → 3B → 2B → ??
WAV_DIR = "wav"
ANN_DIR = "ann"
TARGET_LUFS = -14.0
MAX_SHIFT_SEC = 0.05
TRACKS = [
    ("Keinemusik, Boys Noize - Crazy For It (feat. Vinson)_120BPM_12B_120BPM_12B", "Keinemusik, Boys Noize - Crazy For It (feat. Vinson).wav", "Keinemusik, Boys Noize - Crazy For It (feat. Vinson).txt"),
    ("Korolova_MadeForLove_127BPM_12A_127BPM_12A", "Korolova_MadeForLove.wav", "Korolova_MadeForLove.txt"),
    ("Innellea_InsideYourMind_126BPM_11A_126BPM_11A", "Innellea_InsideYourMind.wav", "Innellea_InsideYourMind.txt"),
    ("MissMonique_IsAnyone_125BPM_11A_125BPM_11A", "MissMonique_IsAnyone.wav", "MissMonique_IsAnyone.txt"),
    ("In the Moment (Adriatique Extended Remix)_124BPM_10A_124BPM_10A", "In the Moment (Adriatique Extended Remix).wav", "In the Moment (Adriatique Extended Remix).txt"),
    ("RafaelCerato_SoundVibrate_126BPM_10B_126BPM_10B", "RafaelCerato_SoundVibrate.wav", "RafaelCerato_SoundVibrate.txt"),
    ("Layton Giordani - Act Of God (ft. Linney & Sarah de Warren) [Extended Mix]_129BPM_10A_129BPM_10A", "Layton Giordani - Act Of God (ft. Linney & Sarah de Warren) [Extended Mix].wav", "Layton Giordani - Act Of God (ft. Linney & Sarah de Warren) [Extended Mix].txt"),
    ("Miss Monique, GENESI & Carl Bee - Nomacita (Extended Mix)_124BPM_9B_124BPM_9B", "Miss Monique, GENESI & Carl Bee - Nomacita (Extended Mix).wav", "Miss Monique, GENESI & Carl Bee - Nomacita (Extended Mix).txt"),
    ("Tale of Us & Ryan Crosson - Big Sins_126BPM_8B_126BPM_8B", "Tale of Us & Ryan Crosson - Big Sins.wav", "Tale of Us & Ryan Crosson - Big Sins.txt"),
    ("Anyma_TillIDie_130BPM_8A_130BPM_8A", "Anyma_TillIDie.wav", "Anyma_TillIDie.txt"),
    ("PACS_NoControl_128BPM_7A_128BPM_7A", "PACS_NoControl.wav", "PACS_NoControl.txt"),
    ("AgentsOfTime_SexyBack_128BPM_6A_128BPM_6A", "AgentsOfTime_SexyBack.wav", "AgentsOfTime_SexyBack.txt"),
    ("Innellea_Unleashed_126BPM_6A_126BPM_6A", "Innellea_Unleashed.wav", "Innellea_Unleashed.txt"),
    ("Rebuke_Ignite_132BPM_6A_132BPM_6A", "Rebuke_Ignite.wav", "Rebuke_Ignite.txt"),
    ("Mathame_MeetMe_128BPM_4A_128BPM_4A", "Mathame_MeetMe.wav", "Mathame_MeetMe.txt"),
    ("Binaryh_Daydream_127BPM_4A_127BPM_4A", "Binaryh_Daydream.wav", "Binaryh_Daydream.txt"),
    ("Shakedown - At Night (Anyma & Layton Giordani Remix) (Extended Mix)_127BPM_4A_127BPM_4A", "Shakedown - At Night (Anyma & Layton Giordani Remix) (Extended Mix).wav", "Shakedown - At Night (Anyma & Layton Giordani Remix) (Extended Mix).txt"),
    ("Cassian, YOTTO, Da Hool – Love Parade (Extended Mix)_128BPM_3B_128BPM_3B", "Cassian, YOTTO, Da Hool – Love Parade (Extended Mix).wav", "Cassian, YOTTO, Da Hool – Love Parade (Extended Mix).txt"),
    ("Yubik_Dragonfly_123BPM_3B_123BPM_3B", "Yubik_Dragonfly.wav", "Yubik_Dragonfly.txt"),
    ("Massano_FadeAway_124BPM_2B_124BPM_2B", "Massano_FadeAway.wav", "Massano_FadeAway.txt"),
    ("John Summit - Focus (feat. CLOVES) [Extended Mix]_128BPM_??_128BPM_??", "John Summit - Focus (feat. CLOVES) [Extended Mix].wav", "John Summit - Focus (feat. CLOVES) [Extended Mix].txt"),
]
